image:
  repository: jimmy7/notes-backend
  tag: latest
  pullPolicy: Always

replicaCount: 2

service:
  port: 8080

env:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_URL: "jdbc:postgresql://192.168.3.16:5432/notesbase"

  ALLOWED_ORIGINS: ""
