apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: prod
spec:
  selector:
    cybernotes: frontend
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  type: ClusterIP