apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    cybernotes: frontend
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 80

  type: ClusterIP
