apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "{{ .Values.letsencrypt.issuerName }}"
    {{- if .Values.ingress.annotations["traefik.ingress.kubernetes.io/router.middlewares"] }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.ingress.annotations["traefik.ingress.kubernetes.io/router.middlewares"] | quote }}
    {{- end }}
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.tls.secretName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend: 
          service:
            name: {{ .Values.ingress.backendService }}
            port:
              number: {{ .Values.ingress.backendPort }}

      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.ingress.frontendService }}
            port: 
              number: {{ .Values.ingress.frontendPort }}
