backend:

  image:
    repository: jimmy7/notes-backend
    tag: latest
    pullPolicy: Always

  replicaCount: 2

  service:
    port: 8080

  env:
    SPRING_PROFILES_ACTIVE: "prod"
    DB_URL: "jdbc:postgresql://192.168.3.16:5432/notesbase"
    ALLOWED_ORIGINS: ""


frontend:

  image:
    repository: jimmy7/notes-frontend
    tag: latest
    pullPolicy: Always

  replicaCount: 2

  service:
    port: 80


letsencrypt:
  create: true
  issuerName: letsencrypt-prod
  email: jonny.cbrigante@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory
  secretName: letsencrypt-prod

tls:
  create: false
  clusterIssuer: letsencrypt-prod
  secretName: cybernotes-tls

ingress:

  host: cybernotes.space

  backendService: backend-service
  backendPort: 8080

  frontendService: frontend-service
  frontendPort: 80

