letsencrypt:
  enable: true
  issuerName: letsencrypt-prod
  email: jonny.cbrigante@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory
  secretName: letsencrypt-prod

tls:
  enable: true
  clusterIssuer: letsencrypt-prod
  secretName: cybernotes-tls

ingress:

  host: cybernotes.space

  backendService: backend-service
  backendPort: 8080

  frontendService: frontend-service
  frontendPort: 80


