{{- if .Values.letsencrypt.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.letsencrypt.issuerName }}
spec:
  acme:
    email: {{ .Values.letsencrypt.issuerName }}
    server: {{ .Values.letsencrypt.server }}
    privateKeySecretRef:
      name: {{ .Values.letsencrypt.secretName }}
    solvers:
    - http01:
        ingress:
          class: traefik