apiVersion: v1 
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    cybernotes: backend
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
  type: ClusterIP