apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: {{ .Values.ingress.backendService }}
          port: {{ .Values.ingress.backendPort }}
      middlewares:
        - name: basic-auth
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ .Values.ingress.frontendService }}
          port: {{ .Values.ingress.frontendPort }}
      middlewares:
        - name: basic-auth
  tls:
    secretName: {{ .Values.tls.secretName }}