{{- if .Values.featureAuth.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: feature-auth
  namespace: {{ .Release.Namespace }}
spec:
  basicAuth:
    secret: feature-auth-secret
    removeHeader: true
{{- end }}
