{{- if .Values.featureAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: feature-auth-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  users: {{ printf "%s:%s" .Values.featureAuth.username .Values.featureAuth.password }}
{{- end }}
