on:
  repository_dispatch:
    types: [deploy-backend-prod, deploy-frontend-prod]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Deploy backend
        if: github.event.action == 'deploy-backend-prod'
        run: |
          export IMAGE="${{ github.event.client_payload.image }}"
          envsubst < k8s/prod/deployments/backend_deployment.yaml | kubectl apply -f -

      - name: Deploy frontend
        if: github.event.action == 'deploy-frontend-prod'
        run: |
          export IMAGE="${{ github.event.client_payload.image }}"
          envsubst < k8s/prod/deployments/frontend_deployment.yaml | kubectl apply -f -

