on:
  repository_dispatch:
    types: [deploy-backend-feature, deploy-frontend-feature]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Go to repo root
        run: |
          cd "$GITHUB_WORKSPACE"
          echo "PWD=$(pwd)"
          ls -la

      - name: Kube config
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Deploy backend
        if: github.event.action == 'deploy-backend-feature'
        run: |
          cd "$GITHUB_WORKSPACE"
          IMAGE_REPO="${{ github.event.client_payload.repository }}"
          IMAGE_TAG="${{ github.event.client_payload.tag }}"
          helm upgrade --install backend-feature ./k8s/helm/backend \
            --namespace feature \
            --values ./k8s/helm/backend/values-feature.yaml \
            --set backend.image.repository="${IMAGE_REPO}" \
            --set backend.image.tag="${IMAGE_TAG}"
            

      - name: Deploy frontend
        if: github.event.action == 'deploy-frontend-feature'
        run: |
          cd "$GITHUB_WORKSPACE"
          IMAGE_REPO="${{ github.event.client_payload.repository }}"
          IMAGE_TAG="${{ github.event.client_payload.tag }}"
          helm upgrade --install frontend-feature ./k8s/helm/frontend \
            --namespace feature \
            --values ./k8s/helm/backend/values-feature.yaml \
            --set frontend.image.repository="${IMAGE_REPO}" \
            --set frontend.image.tag="${IMAGE_TAG}"
