on:
  repository_dispatch:
    types: [deploy-backend-prod, deploy-frontend-prod]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Kube config
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config


      - name: Deploy backend via Helm
        if: github.event.action == 'deploy-backend-prod'
        run: |
          export IMAGE="${{ github.event.client_payload.image }}"
          echo "IMAGE=${IMAGE}"
          helm upgrade --install backend ./k8s/helm/backend \
            --namespace prod \
            --set image.full="${IMAGE}"
            --force
            

      - name: Deploy frontend
        if: github.event.action == 'deploy-frontend-prod'
        run: |
          export IMAGE="${{ github.event.client_payload.image }}"
          echo "IMAGE=${IMAGE}"
          helm upgrade --install frontend ./k8s/helm/frontend \
            --namespace prod \
            --set image.full="${IMAGE}"
            --force

