on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Go to repo root
        run: |
          cd "$GITHUB_WORKSPACE"
          echo "PWD=$(pwd)"
          ls -la

      - name: Kube config
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Deploy ingress
        run: |
          cd "$GITHUB_WORKSPACE"
          IMAGE_REPO="${{ github.event.client_payload.repository }}"
          IMAGE_TAG="${{ github.event.client_payload.tag }}"
          helm upgrade --install ingress-feature ./k8s/helm/feature/ingress \
            --namespace feature \
