on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Go to repo root
        run: |
          cd "$GITHUB_WORKSPACE"
          echo "PWD=$(pwd)"
          ls -la

      - name: Kube config
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Deploy ingress
        run: |
          cd "$GITHUB_WORKSPACE"
          USERNAME="${{ secrets.FEATURE_USER }}"
          PASSWORD_HASH="${{ secrets.FEATURE_PASS}}"
          helm upgrade --install ingress-feature ./k8s/helm/feature/ingress \
            --namespace feature \
            --set auth.users="${USERNAME}:${PASSWORD_HASH}"
