apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: prod
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      cybernotes: frontend
  template:
    metadata:
      labels:
        cybernotes: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.image.full }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: 80